const $=s=>document.querySelector(s);
let lang=localStorage.getItem("market-language")||"zh",alarmEnabled=false,alerted=new Set(),timer,allCandidates=[];
let watchlist=JSON.parse(localStorage.getItem("market-watchlist")||"[]");
const D={
zh:{title:"全市場漲跌異動雷達 AI",autoScan:"每分鐘自動掃描",frames:"分析 5m／15m／30m",preparing:"準備掃描市場…",enableAlarm:"開啟警報",alarmOn:"交易警報已開啟",scanNow:"立即掃描",strongest:"目前最強異動候選",confidence:"模型信心",scanning:"正在掃描多市場",analyzing:"分析中",ranking:"全市場候選排行",asset:"標的",total:"綜合",model:"預判模型","model.1":"• 上漲前蓄勢／下跌前轉弱","model.2":"• 暴漲後回撤／暴跌後反彈","model.3":"• 估算單日波動潛力 ≥5%","model.4":"• 突破位置、RSI、ATR、波動率與量能",planTitle:"目前訊號與交易計畫",loading:"載入市場資料中…",disclaimer:"所有點位皆為模型情境，不是報酬保證；僅供研究，不構成投資建議。",watchTitle:"我的即時關注清單",watchRefresh:"每分鐘獨立更新",watchEmpty:"點選排行中的標的，再按「加入關注」。",addWatch:"＋ 加入即時關注",remove:"移除",waiting:"等待行情…",entry:"入場觀察區",holding:"預計持有",risk:"風險報酬比",invalid:"失效條件",daily:"單日波動潛力",updated:"更新",scanError:"掃描失敗",filter:{all:"全部機會",volatile:"高波動小幣（含 B）",potential:"單日潛力 ≥5%",early:"預先蓄勢／轉弱",reversal:"暴漲跌後反轉",crypto:"大型加密貨幣",fx:"外匯",commodity:"黃金／原油"},setup:{"暴漲後回撤":"暴漲後回撤","暴跌後反彈":"暴跌後反彈","上漲前蓄勢":"上漲前蓄勢","下跌前轉弱":"下跌前轉弱","多頭加速":"多頭加速","空頭加速":"空頭加速"},market:{"加密貨幣":"加密貨幣","高波動貨幣":"高波動貨幣","外匯":"外匯","商品":"商品","指數":"指數"}},
en:{title:"Global Market Move Radar AI",autoScan:"Auto scan every minute",frames:"Analyze 5m / 15m / 30m",preparing:"Preparing market scan…",enableAlarm:"Enable alerts",alarmOn:"Trading alerts enabled",scanNow:"Scan now",strongest:"Strongest current candidate",confidence:"Model confidence",scanning:"Scanning multiple markets",analyzing:"Analyzing",ranking:"Market candidate ranking",asset:"Asset",total:"Total",model:"Forecast model","model.1":"• Pre-breakout accumulation / pre-drop weakness","model.2":"• Pullback after surge / rebound after selloff","model.3":"• Estimated daily move potential ≥5%","model.4":"• Breakout, RSI, ATR, volatility and activity",planTitle:"Signal and scenario plan",loading:"Loading market data…",disclaimer:"All levels are model scenarios, not guaranteed returns. Research only; not investment advice.",watchTitle:"My live watchlist",watchRefresh:"Independently refreshed every minute",watchEmpty:"Select an asset and click Add to watchlist.",addWatch:"+ Add to watchlist",remove:"Remove",waiting:"Waiting for data…",entry:"Entry zone",holding:"Expected duration",risk:"Risk/reward",invalid:"Invalidation",daily:"Daily move potential",updated:"Updated",scanError:"Scan failed",filter:{all:"All opportunities",volatile:"High-volatility tokens (incl. B)",potential:"Daily potential ≥5%",early:"Early setup",reversal:"Post-move reversal",crypto:"Large-cap crypto",fx:"Forex",commodity:"Gold / Oil"},setup:{"暴漲後回撤":"Post-surge pullback","暴跌後反彈":"Post-selloff rebound","上漲前蓄勢":"Pre-breakout accumulation","下跌前轉弱":"Pre-drop weakness","多頭加速":"Bullish acceleration","空頭加速":"Bearish acceleration"},market:{"加密貨幣":"Crypto","高波動貨幣":"High-volatility token","外匯":"Forex","商品":"Commodity","指數":"Index"}},
es:{title:"Radar Global de Movimientos AI",autoScan:"Escaneo automático cada minuto",frames:"Analiza 5m / 15m / 30m",preparing:"Preparando el escaneo…",enableAlarm:"Activar alertas",alarmOn:"Alertas activadas",scanNow:"Escanear ahora",strongest:"Candidato más fuerte",confidence:"Confianza del modelo",scanning:"Escaneando mercados",analyzing:"Analizando",ranking:"Clasificación de candidatos",asset:"Activo",total:"Total",model:"Modelo predictivo","model.1":"• Acumulación alcista / debilidad bajista","model.2":"• Retroceso tras subida / rebote tras caída","model.3":"• Potencial diario estimado ≥5%","model.4":"• Ruptura, RSI, ATR, volatilidad y actividad",planTitle:"Señal y plan de escenario",loading:"Cargando datos…",disclaimer:"Los niveles son escenarios del modelo, no retornos garantizados. Solo investigación.",watchTitle:"Mi lista en vivo",watchRefresh:"Actualización independiente cada minuto",watchEmpty:"Selecciona un activo y añádelo a seguimiento.",addWatch:"+ Añadir a seguimiento",remove:"Quitar",waiting:"Esperando datos…",entry:"Zona de entrada",holding:"Duración estimada",risk:"Riesgo/beneficio",invalid:"Invalidación",daily:"Potencial diario",updated:"Actualizado",scanError:"Error de escaneo",filter:{all:"Todas",volatile:"Tokens volátiles (incl. B)",potential:"Potencial diario ≥5%",early:"Señal temprana",reversal:"Reversión",crypto:"Cripto principal",fx:"Forex",commodity:"Oro / Petróleo"},setup:{"暴漲後回撤":"Retroceso tras subida","暴跌後反彈":"Rebote tras caída","上漲前蓄勢":"Acumulación alcista","下跌前轉弱":"Debilidad bajista","多頭加速":"Aceleración alcista","空頭加速":"Aceleración bajista"},market:{"加密貨幣":"Cripto","高波動貨幣":"Token volátil","外匯":"Forex","商品":"Materia prima","指數":"Índice"}},
ja:{title:"全市場変動レーダー AI",autoScan:"1分ごとに自動スキャン",frames:"5分／15分／30分を分析",preparing:"市場スキャンを準備中…",enableAlarm:"アラートを有効化",alarmOn:"取引アラート有効",scanNow:"今すぐスキャン",strongest:"現在の最有力候補",confidence:"モデル信頼度",scanning:"複数市場をスキャン中",analyzing:"分析中",ranking:"市場候補ランキング",asset:"銘柄",total:"総合",model:"予測モデル","model.1":"• 上昇前の蓄積／下落前の弱含み","model.2":"• 急騰後の反落／急落後の反発","model.3":"• 推定日次変動ポテンシャル ≥5%","model.4":"• ブレイク、RSI、ATR、変動率、出来高",planTitle:"シグナルとシナリオ計画",loading:"市場データを読込中…",disclaimer:"全価格はモデルシナリオで、利益を保証しません。調査目的のみ。",watchTitle:"リアルタイム監視リスト",watchRefresh:"1分ごとに個別更新",watchEmpty:"銘柄を選び、監視リストに追加してください。",addWatch:"＋ 監視リストに追加",remove:"削除",waiting:"データ待機中…",entry:"エントリー範囲",holding:"想定保有時間",risk:"リスク・リワード",invalid:"無効条件",daily:"日次変動ポテンシャル",updated:"更新",scanError:"スキャン失敗",filter:{all:"すべて",volatile:"高変動トークン（B含む）",potential:"日次ポテンシャル ≥5%",early:"初期シグナル",reversal:"反転",crypto:"主要暗号資産",fx:"FX",commodity:"金／原油"},setup:{"暴漲後回撤":"急騰後の反落","暴跌後反彈":"急落後の反発","上漲前蓄勢":"上昇前の蓄積","下跌前轉弱":"下落前の弱含み","多頭加速":"上昇加速","空頭加速":"下落加速"},market:{"加密貨幣":"暗号資産","高波動貨幣":"高変動トークン","外匯":"FX","商品":"商品","指數":"指数"}},
ko:{title:"글로벌 시장 변동 레이더 AI",autoScan:"1분마다 자동 스캔",frames:"5분 / 15분 / 30분 분석",preparing:"시장 스캔 준비 중…",enableAlarm:"알림 켜기",alarmOn:"거래 알림 활성화",scanNow:"지금 스캔",strongest:"현재 최강 후보",confidence:"모델 신뢰도",scanning:"여러 시장 스캔 중",analyzing:"분석 중",ranking:"시장 후보 순위",asset:"자산",total:"종합",model:"예측 모델","model.1":"• 상승 전 축적 / 하락 전 약세","model.2":"• 급등 후 조정 / 급락 후 반등","model.3":"• 예상 일일 변동 잠재력 ≥5%","model.4":"• 돌파, RSI, ATR, 변동성 및 거래 활동",planTitle:"신호 및 시나리오 계획",loading:"시장 데이터 로딩 중…",disclaimer:"모든 가격은 모델 시나리오이며 수익을 보장하지 않습니다. 연구용입니다.",watchTitle:"실시간 관심 목록",watchRefresh:"1분마다 개별 업데이트",watchEmpty:"자산을 선택한 후 관심 목록에 추가하세요.",addWatch:"+ 관심 목록 추가",remove:"삭제",waiting:"데이터 대기 중…",entry:"진입 구간",holding:"예상 보유 기간",risk:"손익비",invalid:"무효 조건",daily:"일일 변동 잠재력",updated:"업데이트",scanError:"스캔 실패",filter:{all:"전체 기회",volatile:"고변동 토큰(B 포함)",potential:"일일 잠재력 ≥5%",early:"초기 신호",reversal:"반전",crypto:"주요 암호화폐",fx:"외환",commodity:"금 / 원유"},setup:{"暴漲後回撤":"급등 후 조정","暴跌後反彈":"급락 후 반등","上漲前蓄勢":"상승 전 축적","下跌前轉弱":"하락 전 약세","多頭加速":"상승 가속","空頭加速":"하락 가속"},market:{"加密貨幣":"암호화폐","高波動貨幣":"고변동 토큰","外匯":"외환","商品":"상품","指數":"지수"}}
};
const t=(key)=>{const parts=key.split(".");let v=D[lang];for(const p of parts)v=v?.[p];return v??D.zh[key]??key};
const setup=c=>D[lang].setup[c.setup]||c.setup,market=c=>D[lang].market[c.market]||c.market;
const cls=n=>n>=82?"hot":n>=68?"mid":"",money=n=>!n?market({market:"商品"}):n>=1e9?`$${(n/1e9).toFixed(1)}B`:`$${(n/1e6).toFixed(0)}M`;
const price=n=>Number(n).toLocaleString(lang==="zh"?"zh-TW":lang,{maximumFractionDigits:n<1?6:n<100?4:2});
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));$("#language").value=lang;$("#alarm").textContent=alarmEnabled?t("alarmOn"):t("enableAlarm");render();renderWatchlist()}
function beep(d){const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=d==="down"?330:880;g.gain.setValueAtTime(.16,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.7);o.start();o.stop(a.currentTime+.7)}
function notify(c){const key=c.symbol+c.setup;if(!alarmEnabled||(!c.potential5&&c.score<82)||alerted.has(key))return;alerted.add(key);beep(c.setupDirection);if(Notification.permission==="granted")new Notification("Market Pulse AI",{body:`${c.label||c.symbol}: ${setup(c)} · ${t("confidence")} ${c.confidence}%`})}
function saveWatch(c){const key=`${c.source}:${c.symbol}`;if(!watchlist.some(x=>x.key===key))watchlist.push({key,source:c.source,symbol:c.symbol,data:c});localStorage.setItem("market-watchlist",JSON.stringify(watchlist));renderWatchlist()}
function removeWatch(key){watchlist=watchlist.filter(x=>x.key!==key);localStorage.setItem("market-watchlist",JSON.stringify(watchlist));renderWatchlist()}
function renderWatchlist(){if(!$("#watchlist"))return;if(!watchlist.length){$("#watchlist").innerHTML=`<p class="summary">${t("watchEmpty")}</p>`;return}$("#watchlist").innerHTML=watchlist.map(x=>{const c=x.data;if(!c)return `<div class="watchrow"><b>${x.symbol}</b><span>${t("waiting")}</span></div>`;return `<div class="watchrow"><span><b>${c.label||c.symbol}</b><small>${c.source||market(c)}</small></span><span class="direction ${c.setupDirection}">${setup(c)}</span><span>${t("confidence")} <b>${c.confidence}%</b></span><span>${t("entry")}<br><b>${price(c.plan.entryLow)}</b></span><span>TP1<br><b>${price(c.plan.tp1)}</b></span><span>SL<br><b>${price(c.plan.sl)}</b></span><button data-remove="${x.key}">${t("remove")}</button></div>`}).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>removeWatch(b.dataset.remove))}
async function refreshWatchlist(){await Promise.all(watchlist.map(async item=>{let fresh=allCandidates.find(c=>c.symbol===item.symbol&&c.source===item.source);if(!fresh&&item.source!=="Yahoo")try{fresh=await fetch(`/api/analyze?symbol=${item.symbol}&source=${item.source}`).then(r=>r.json())}catch{}if(fresh&&!fresh.error)item.data=fresh}));localStorage.setItem("market-watchlist",JSON.stringify(watchlist));renderWatchlist()}
function explain(c){const p=c.plan;$("#summary").innerHTML=`<p><b>${c.label||c.symbol}</b>：<span class="direction ${c.setupDirection}">${setup(c)}</span> · ${t("confidence")} <b>${c.confidence}%</b></p><div class="plan"><span>${t("entry")}<b>${price(p.entryLow)}–${price(p.entryHigh)}</b></span><span>TP1 / TP2<b>${price(p.tp1)} / ${price(p.tp2)}</b></span><span>SL<b>${price(p.sl)}</b></span></div><p>${t("holding")}: <b>${c.early?"6–24h":c.setup.includes("後")?"2–12h":"1–6h"}</b> · ${t("risk")} ${p.riskReward1.toFixed(2)}</p><p>${t("daily")}: ${c.projectedDaily.toFixed(2)}%</p><button class="addwatch" id="addwatch">${t("addWatch")}</button>`;$("#addwatch").onclick=()=>saveWatch(c)}
function filtered(){const type=$("#filter").value;if(type==="potential5")return allCandidates.filter(c=>c.potential5);if(type==="early")return allCandidates.filter(c=>c.early);if(type==="reversal")return allCandidates.filter(c=>c.setup.includes("後"));if(type!=="all")return allCandidates.filter(c=>c.market===type);return allCandidates}
function render(){if(!$("#rankingList")||!allCandidates.length)return;const list=filtered().slice(0,20);if(!list.length){$("#rankingList").innerHTML=`<p>${t("waiting")}</p>`;return}$("#rankingList").innerHTML=list.map((c,i)=>`<div class="rank ${c.setupDirection}" data-i="${i}"><span><b>${c.label||c.symbol}</b><small>${setup(c)} · ${c.confidence}%</small></span>${["5m","15m","30m"].map(x=>`<span class="pill ${cls(c.frames[x].score)}">${c.frames[x].score}</span>`).join("")}<span class="pill ${cls(c.score)}"><b>${c.score}</b> ${c.setupDirection==="up"?"▲":"▼"}</span></div>`).join("");const top=list[0];$("#leader").textContent=top.label||top.symbol;$("#score").textContent=top.confidence;$("#verdict").textContent=setup(top);$("#verdict").className=top.setupDirection;$("#reason").textContent=`${t("daily")} ${top.projectedDaily.toFixed(1)}%`;explain(top);document.querySelectorAll(".rank").forEach(el=>el.onclick=()=>explain(list[+el.dataset.i]))}
async function scan(){clearTimeout(timer);$("#refresh").disabled=true;try{const [crypto,special]=await Promise.all([fetch("/api/scan").then(r=>r.json()),fetch("/api/special").then(r=>r.json())]);if(crypto.error)throw Error(crypto.error);allCandidates=[...crypto.candidates,...(special.candidates||[])].sort((a,b)=>b.confidence-a.confidence);$("#universe").textContent=`${crypto.universe} markets · ${crypto.highVolatilityCount||0} high-vol`;$("#updated").textContent=`${t("updated")} ${new Date().toLocaleTimeString()}`;render();allCandidates.forEach(notify);await refreshWatchlist()}catch(e){$("#summary").textContent=`${t("scanError")}: ${e.message}`}finally{$("#refresh").disabled=false;timer=setTimeout(scan,60000)}}
$("#language").onchange=e=>{lang=e.target.value;localStorage.setItem("market-language",lang);applyLanguage()};$("#filter").onchange=render;$("#alarm").onclick=async()=>{if("Notification"in window&&Notification.permission==="default")await Notification.requestPermission();alarmEnabled=!alarmEnabled;$("#alarm").textContent=alarmEnabled?t("alarmOn"):t("enableAlarm");if(alarmEnabled)beep("up")};$("#refresh").onclick=scan;applyLanguage();scan();
